### ISSUE TITLE
第一次使用，该如何完美使用功能

### ISSUE THREAD

**Issue by maajiko** [assimon/captcha-bot#2]
项目需要数据库吗，该如何使用，加群验证功能好像无法使用，我不知道是不是我配置问题😭

![IMG_20221004_213129.jpg](https://user-images.githubusercontent.com/83452696/193832596-8fbe72b2-8f65-46ee-907f-04ffe06a70d0.jpg)

**Comment by assimon** [comment]
没有成功初始化sqliteDB

**Comment by maajiko** [comment]
其他功能正常了，入群验证应该不需要另外配置吧，直接拉入群设置管理员就行了吗，我测试了没效果没反应
