### ISSUE TITLE
openssl无法解析，并且程序似乎无法使

### ISSUE THREAD

**Issue by selfmakeit** [assimon/captcha-bot#3]
`1. openssl解析：
     bad decrypt
40778BE7AC7F0000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:../providers/implementations/ciphers/ciphercommon_block.c:129:

2.程序无法使用：bot添加到群之后 bot为管理员 并且/ping有反应，但是新成员入群之后bot无反应，也没有报任何错误
`

**Comment by assimon** [comment]
这个是服务器环境的问题，检查一下服务器证书

**Comment by hczjxhdyz** [comment]
我的openssl可以解析，但是也出现了 新成员入群后bot无反应的问题，也没任何报错，ping有反应

**Comment by assimon** [comment]
没有反应是因为机器人botfather的权限没有给机器人

**Comment by seekvps** [comment]
debian12默认的openssl是3开头版本，实测1.1.1也无法解码，0.9.7解码成功。推荐直接用docker镜像 tlsprint/openssl:0.9.7

**Comment by lollipopkit** [comment]
经过大小对比，原文件应该是：
https://github.com/importcjj/sensitive?tab=readme-ov-file#loadnetworddict
