### ISSUE TITLE
当违禁词包含!#*()-+={}其中之一时, 消息不会被删除

### ISSUE THREAD

**Issue by sx1024** [assimon/captcha-bot#7]
当违禁词包含!#*()-+={}其中之一时, 会将该用户禁言, 但是他的垃圾广告不会被删除.
已测试违禁词包含@$%^&时没事. 可以封禁的同时正常将该消息删除. 其他的符号未知... 没测试

例如: 
违禁词:  日-赚    主-页
如果发送: 日-赚-一-万, 看-主-页. 此时会仅禁言用户. 消息会遗留在群里.

如果设置违禁词为单个字. 误触会有点高.

**Comment by assimon** [comment]
这个就不是单纯的拆词匹配能解决了
