### ISSUE TITLE
违禁词可被绕过

### ISSUE THREAD

**Issue by sx1024** [assimon/captcha-bot#8]
近期出现了一批这样发广告的:
/start /settings /config + 广告
可绕过机器人的检查

我试了试
/start + 违禁词
/ping + 违禁词
/add_ad + 违禁词
...............
均可成功发送广告

**Comment by assimon** [comment]
确实有可能绕过

**Comment by assimon** [comment]
已经修复 了，可以拉最新master编译后使用

> 近期出现了一批这样发广告的: /start /settings /config + 广告 可绕过机器人的检查
> 
> 我试了试 /start + 违禁词 /ping + 违禁词 /add_ad + 违禁词 ............... 均可成功发送广告
